# Generated by Django 6.0 on 2025-12-29 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet de Extranjeria'), ('PASSPORT', 'Pasaporte')], default='RUC', max_length=10, verbose_name='Tipo Documento')),
                ('document_number', models.CharField(max_length=20, unique=True, verbose_name='Numero Documento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono movil')),
                ('address', models.CharField(blank=True, max_length=350, null=True, verbose_name='Direccion')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Pagina Web')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Es Proveedor')),
                ('is_costumer', models.BooleanField(default=False, verbose_name='Es Trabajador')),
                ('is_carrier', models.BooleanField(default=False, verbose_name='Es Transportista')),
                ('is_shareholder', models.BooleanField(default=False, verbose_name='Es Accionista')),
                ('is_financial_entity', models.BooleanField(default=False, verbose_name='Es Entidad Financiera')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner', to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
            },
        ),
    ]
